name: CI

on:
  push:
    branches:
      - main  # Change to your default branch if necessary
  pull_request:
    branches:
      - main  # Runs on PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Specify your Java version
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Ensure gradlew is executable for Employee
        run: chmod +x ./employee/gradlew

      - name: Build Employee Module
        working-directory: ./employee
        run: ./gradlew build

      - name: Ensure gradlew is executable for Identity
        run: chmod +x ./identity/gradlew

      - name: Build Identity Module
        working-directory: ./identity
        run: ./gradlew build

      - name: Build UI Module
        working-directory: ./ui
        run: npm install && npm test
